// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/v1/task.proto

package taskv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestartTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartTaskRequest) Reset() {
	*x = RestartTaskRequest{}
	mi := &file_api_proto_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartTaskRequest) ProtoMessage() {}

func (x *RestartTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartTaskRequest.ProtoReflect.Descriptor instead.
func (*RestartTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *RestartTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type RestartTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartTaskResponse) Reset() {
	*x = RestartTaskResponse{}
	mi := &file_api_proto_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartTaskResponse) ProtoMessage() {}

func (x *RestartTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartTaskResponse.ProtoReflect.Descriptor instead.
func (*RestartTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *RestartTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_api_proto_v1_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{2}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelTaskRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CancelTaskRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_api_proto_v1_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{3}
}

func (x *CancelTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Ns            string                 `protobuf:"bytes,3,opt,name=ns,proto3" json:"ns,omitempty"`
	Db            string                 `protobuf:"bytes,4,opt,name=db,proto3" json:"db,omitempty"`
	Auth          string                 `protobuf:"bytes,5,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterConnectionRequest) Reset() {
	*x = RegisterConnectionRequest{}
	mi := &file_api_proto_v1_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConnectionRequest) ProtoMessage() {}

func (x *RegisterConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConnectionRequest.ProtoReflect.Descriptor instead.
func (*RegisterConnectionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterConnectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterConnectionRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RegisterConnectionRequest) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *RegisterConnectionRequest) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *RegisterConnectionRequest) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

type RegisterConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DaprPath      string                 `protobuf:"bytes,3,opt,name=dapr_path,json=daprPath,proto3" json:"dapr_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterConnectionResponse) Reset() {
	*x = RegisterConnectionResponse{}
	mi := &file_api_proto_v1_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConnectionResponse) ProtoMessage() {}

func (x *RegisterConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConnectionResponse.ProtoReflect.Descriptor instead.
func (*RegisterConnectionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterConnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterConnectionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterConnectionResponse) GetDaprPath() string {
	if x != nil {
		return x.DaprPath
	}
	return ""
}

type SearchLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Before        int32                  `protobuf:"varint,3,opt,name=before,proto3" json:"before,omitempty"`
	After         int32                  `protobuf:"varint,4,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLogsRequest) Reset() {
	*x = SearchLogsRequest{}
	mi := &file_api_proto_v1_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLogsRequest) ProtoMessage() {}

func (x *SearchLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLogsRequest.ProtoReflect.Descriptor instead.
func (*SearchLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{6}
}

func (x *SearchLogsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SearchLogsRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *SearchLogsRequest) GetBefore() int32 {
	if x != nil {
		return x.Before
	}
	return 0
}

func (x *SearchLogsRequest) GetAfter() int32 {
	if x != nil {
		return x.After
	}
	return 0
}

type GlobalSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Ext           string                 `protobuf:"bytes,3,opt,name=ext,proto3" json:"ext,omitempty"`
	Before        int32                  `protobuf:"varint,4,opt,name=before,proto3" json:"before,omitempty"`
	After         int32                  `protobuf:"varint,5,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalSearchRequest) Reset() {
	*x = GlobalSearchRequest{}
	mi := &file_api_proto_v1_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalSearchRequest) ProtoMessage() {}

func (x *GlobalSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalSearchRequest.ProtoReflect.Descriptor instead.
func (*GlobalSearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{7}
}

func (x *GlobalSearchRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GlobalSearchRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *GlobalSearchRequest) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *GlobalSearchRequest) GetBefore() int32 {
	if x != nil {
		return x.Before
	}
	return 0
}

func (x *GlobalSearchRequest) GetAfter() int32 {
	if x != nil {
		return x.After
	}
	return 0
}

type SearchMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	LineNum       int32                  `protobuf:"varint,2,opt,name=line_num,json=lineNum,proto3" json:"line_num,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	ContextBefore []string               `protobuf:"bytes,4,rep,name=context_before,json=contextBefore,proto3" json:"context_before,omitempty"`
	ContextAfter  []string               `protobuf:"bytes,5,rep,name=context_after,json=contextAfter,proto3" json:"context_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMatch) Reset() {
	*x = SearchMatch{}
	mi := &file_api_proto_v1_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMatch) ProtoMessage() {}

func (x *SearchMatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMatch.ProtoReflect.Descriptor instead.
func (*SearchMatch) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{8}
}

func (x *SearchMatch) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SearchMatch) GetLineNum() int32 {
	if x != nil {
		return x.LineNum
	}
	return 0
}

func (x *SearchMatch) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SearchMatch) GetContextBefore() []string {
	if x != nil {
		return x.ContextBefore
	}
	return nil
}

func (x *SearchMatch) GetContextAfter() []string {
	if x != nil {
		return x.ContextAfter
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*SearchMatch         `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_proto_v1_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{9}
}

func (x *SearchResponse) GetMatches() []*SearchMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type SubmitTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Env           map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkDir       string                 `protobuf:"bytes,3,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`                                           // taskfile or infra
	Project       string                 `protobuf:"bytes,5,opt,name=project,proto3" json:"project,omitempty"`                                     // pulumi project name
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`                                           // task name or stack name
	IsLongRunning bool                   `protobuf:"varint,7,opt,name=is_long_running,json=isLongRunning,proto3" json:"is_long_running,omitempty"` // true for persistent daemon tasks
	Group         string                 `protobuf:"bytes,8,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskRequest) Reset() {
	*x = SubmitTaskRequest{}
	mi := &file_api_proto_v1_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskRequest) ProtoMessage() {}

func (x *SubmitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{10}
}

func (x *SubmitTaskRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SubmitTaskRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *SubmitTaskRequest) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *SubmitTaskRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SubmitTaskRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *SubmitTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubmitTaskRequest) GetIsLongRunning() bool {
	if x != nil {
		return x.IsLongRunning
	}
	return false
}

func (x *SubmitTaskRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type SubmitTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AccessUrl     string                 `protobuf:"bytes,2,opt,name=access_url,json=accessUrl,proto3" json:"access_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskResponse) Reset() {
	*x = SubmitTaskResponse{}
	mi := &file_api_proto_v1_task_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResponse) ProtoMessage() {}

func (x *SubmitTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResponse.ProtoReflect.Descriptor instead.
func (*SubmitTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubmitTaskResponse) GetAccessUrl() string {
	if x != nil {
		return x.AccessUrl
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_api_proto_v1_task_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{12}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	AccessUrl     string                 `protobuf:"bytes,6,opt,name=access_url,json=accessUrl,proto3" json:"access_url,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Command       string                 `protobuf:"bytes,8,opt,name=command,proto3" json:"command,omitempty"`
	Type          string                 `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	WorkDir       string                 `protobuf:"bytes,10,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	Group         string                 `protobuf:"bytes,11,opt,name=group,proto3" json:"group,omitempty"`
	LogPath       string                 `protobuf:"bytes,12,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_api_proto_v1_task_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{13}
}

func (x *GetTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTaskResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetTaskResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetTaskResponse) GetAccessUrl() string {
	if x != nil {
		return x.AccessUrl
	}
	return ""
}

func (x *GetTaskResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTaskResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *GetTaskResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetTaskResponse) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *GetTaskResponse) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GetTaskResponse) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

type GetTaskLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TailLines     int64                  `protobuf:"varint,2,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskLogsRequest) Reset() {
	*x = GetTaskLogsRequest{}
	mi := &file_api_proto_v1_task_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskLogsRequest) ProtoMessage() {}

func (x *GetTaskLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskLogsRequest.ProtoReflect.Descriptor instead.
func (*GetTaskLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{14}
}

func (x *GetTaskLogsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskLogsRequest) GetTailLines() int64 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

type GetTaskLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskLogsResponse) Reset() {
	*x = GetTaskLogsResponse{}
	mi := &file_api_proto_v1_task_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskLogsResponse) ProtoMessage() {}

func (x *GetTaskLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskLogsResponse.ProtoReflect.Descriptor instead.
func (*GetTaskLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{15}
}

func (x *GetTaskLogsResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_api_proto_v1_task_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{16}
}

func (x *ListTasksRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListTasksRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListTasksRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*GetTaskResponse     `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_api_proto_v1_task_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_task_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_task_proto_rawDescGZIP(), []int{17}
}

func (x *ListTasksResponse) GetTasks() []*GetTaskResponse {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_api_proto_v1_task_proto protoreflect.FileDescriptor

const file_api_proto_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/v1/task.proto\x12\atask.v1\"-\n" +
	"\x12RestartTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\".\n" +
	"\x13RestartTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"X\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\".\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"u\n" +
	"\x19RegisterConnectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x0e\n" +
	"\x02ns\x18\x03 \x01(\tR\x02ns\x12\x0e\n" +
	"\x02db\x18\x04 \x01(\tR\x02db\x12\x12\n" +
	"\x04auth\x18\x05 \x01(\tR\x04auth\"g\n" +
	"\x1aRegisterConnectionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tdapr_path\x18\x03 \x01(\tR\bdaprPath\"t\n" +
	"\x11SearchLogsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12\x16\n" +
	"\x06before\x18\x03 \x01(\x05R\x06before\x12\x14\n" +
	"\x05after\x18\x04 \x01(\x05R\x05after\"\x83\x01\n" +
	"\x13GlobalSearchRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12\x10\n" +
	"\x03ext\x18\x03 \x01(\tR\x03ext\x12\x16\n" +
	"\x06before\x18\x04 \x01(\x05R\x06before\x12\x14\n" +
	"\x05after\x18\x05 \x01(\x05R\x05after\"\x9c\x01\n" +
	"\vSearchMatch\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\bline_num\x18\x02 \x01(\x05R\alineNum\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12%\n" +
	"\x0econtext_before\x18\x04 \x03(\tR\rcontextBefore\x12#\n" +
	"\rcontext_after\x18\x05 \x03(\tR\fcontextAfter\"@\n" +
	"\x0eSearchResponse\x12.\n" +
	"\amatches\x18\x01 \x03(\v2\x14.task.v1.SearchMatchR\amatches\"\xb7\x02\n" +
	"\x11SubmitTaskRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x125\n" +
	"\x03env\x18\x02 \x03(\v2#.task.v1.SubmitTaskRequest.EnvEntryR\x03env\x12\x19\n" +
	"\bwork_dir\x18\x03 \x01(\tR\aworkDir\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\aproject\x18\x05 \x01(\tR\aproject\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12&\n" +
	"\x0fis_long_running\x18\a \x01(\bR\risLongRunning\x12\x14\n" +
	"\x05group\x18\b \x01(\tR\x05group\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x12SubmitTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"access_url\x18\x02 \x01(\tR\taccessUrl\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xc3\x02\n" +
	"\x0fGetTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"access_url\x18\x06 \x01(\tR\taccessUrl\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\b \x01(\tR\acommand\x12\x12\n" +
	"\x04type\x18\t \x01(\tR\x04type\x12\x19\n" +
	"\bwork_dir\x18\n" +
	" \x01(\tR\aworkDir\x12\x14\n" +
	"\x05group\x18\v \x01(\tR\x05group\x12\x19\n" +
	"\blog_path\x18\f \x01(\tR\alogPath\"L\n" +
	"\x12GetTaskLogsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x02 \x01(\x03R\ttailLines\"/\n" +
	"\x13GetTaskLogsResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"L\n" +
	"\x10ListTasksRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\"C\n" +
	"\x11ListTasksResponse\x12.\n" +
	"\x05tasks\x18\x01 \x03(\v2\x18.task.v1.GetTaskResponseR\x05tasks2\x9a\x05\n" +
	"\vTaskService\x12E\n" +
	"\n" +
	"SubmitTask\x12\x1a.task.v1.SubmitTaskRequest\x1a\x1b.task.v1.SubmitTaskResponse\x12<\n" +
	"\aGetTask\x12\x17.task.v1.GetTaskRequest\x1a\x18.task.v1.GetTaskResponse\x12H\n" +
	"\vGetTaskLogs\x12\x1b.task.v1.GetTaskLogsRequest\x1a\x1c.task.v1.GetTaskLogsResponse\x12A\n" +
	"\n" +
	"SearchLogs\x12\x1a.task.v1.SearchLogsRequest\x1a\x17.task.v1.SearchResponse\x12E\n" +
	"\fGlobalSearch\x12\x1c.task.v1.GlobalSearchRequest\x1a\x17.task.v1.SearchResponse\x12B\n" +
	"\tListTasks\x12\x19.task.v1.ListTasksRequest\x1a\x1a.task.v1.ListTasksResponse\x12H\n" +
	"\vRestartTask\x12\x1b.task.v1.RestartTaskRequest\x1a\x1c.task.v1.RestartTaskResponse\x12E\n" +
	"\n" +
	"CancelTask\x12\x1a.task.v1.CancelTaskRequest\x1a\x1b.task.v1.CancelTaskResponse\x12]\n" +
	"\x12RegisterConnection\x12\".task.v1.RegisterConnectionRequest\x1a#.task.v1.RegisterConnectionResponseB\x98\x01\n" +
	"\vcom.task.v1B\tTaskProtoP\x01ZAgithub.com/qtopie/copilot-infra/pkg/api/proto/api/proto/v1;taskv1\xa2\x02\x03TXX\xaa\x02\aTask.V1\xca\x02\aTask\\V1\xe2\x02\x13Task\\V1\\GPBMetadata\xea\x02\bTask::V1b\x06proto3"

var (
	file_api_proto_v1_task_proto_rawDescOnce sync.Once
	file_api_proto_v1_task_proto_rawDescData []byte
)

func file_api_proto_v1_task_proto_rawDescGZIP() []byte {
	file_api_proto_v1_task_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_task_proto_rawDesc), len(file_api_proto_v1_task_proto_rawDesc)))
	})
	return file_api_proto_v1_task_proto_rawDescData
}

var file_api_proto_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_proto_v1_task_proto_goTypes = []any{
	(*RestartTaskRequest)(nil),         // 0: task.v1.RestartTaskRequest
	(*RestartTaskResponse)(nil),        // 1: task.v1.RestartTaskResponse
	(*CancelTaskRequest)(nil),          // 2: task.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil),         // 3: task.v1.CancelTaskResponse
	(*RegisterConnectionRequest)(nil),  // 4: task.v1.RegisterConnectionRequest
	(*RegisterConnectionResponse)(nil), // 5: task.v1.RegisterConnectionResponse
	(*SearchLogsRequest)(nil),          // 6: task.v1.SearchLogsRequest
	(*GlobalSearchRequest)(nil),        // 7: task.v1.GlobalSearchRequest
	(*SearchMatch)(nil),                // 8: task.v1.SearchMatch
	(*SearchResponse)(nil),             // 9: task.v1.SearchResponse
	(*SubmitTaskRequest)(nil),          // 10: task.v1.SubmitTaskRequest
	(*SubmitTaskResponse)(nil),         // 11: task.v1.SubmitTaskResponse
	(*GetTaskRequest)(nil),             // 12: task.v1.GetTaskRequest
	(*GetTaskResponse)(nil),            // 13: task.v1.GetTaskResponse
	(*GetTaskLogsRequest)(nil),         // 14: task.v1.GetTaskLogsRequest
	(*GetTaskLogsResponse)(nil),        // 15: task.v1.GetTaskLogsResponse
	(*ListTasksRequest)(nil),           // 16: task.v1.ListTasksRequest
	(*ListTasksResponse)(nil),          // 17: task.v1.ListTasksResponse
	nil,                                // 18: task.v1.SubmitTaskRequest.EnvEntry
}
var file_api_proto_v1_task_proto_depIdxs = []int32{
	8,  // 0: task.v1.SearchResponse.matches:type_name -> task.v1.SearchMatch
	18, // 1: task.v1.SubmitTaskRequest.env:type_name -> task.v1.SubmitTaskRequest.EnvEntry
	13, // 2: task.v1.ListTasksResponse.tasks:type_name -> task.v1.GetTaskResponse
	10, // 3: task.v1.TaskService.SubmitTask:input_type -> task.v1.SubmitTaskRequest
	12, // 4: task.v1.TaskService.GetTask:input_type -> task.v1.GetTaskRequest
	14, // 5: task.v1.TaskService.GetTaskLogs:input_type -> task.v1.GetTaskLogsRequest
	6,  // 6: task.v1.TaskService.SearchLogs:input_type -> task.v1.SearchLogsRequest
	7,  // 7: task.v1.TaskService.GlobalSearch:input_type -> task.v1.GlobalSearchRequest
	16, // 8: task.v1.TaskService.ListTasks:input_type -> task.v1.ListTasksRequest
	0,  // 9: task.v1.TaskService.RestartTask:input_type -> task.v1.RestartTaskRequest
	2,  // 10: task.v1.TaskService.CancelTask:input_type -> task.v1.CancelTaskRequest
	4,  // 11: task.v1.TaskService.RegisterConnection:input_type -> task.v1.RegisterConnectionRequest
	11, // 12: task.v1.TaskService.SubmitTask:output_type -> task.v1.SubmitTaskResponse
	13, // 13: task.v1.TaskService.GetTask:output_type -> task.v1.GetTaskResponse
	15, // 14: task.v1.TaskService.GetTaskLogs:output_type -> task.v1.GetTaskLogsResponse
	9,  // 15: task.v1.TaskService.SearchLogs:output_type -> task.v1.SearchResponse
	9,  // 16: task.v1.TaskService.GlobalSearch:output_type -> task.v1.SearchResponse
	17, // 17: task.v1.TaskService.ListTasks:output_type -> task.v1.ListTasksResponse
	1,  // 18: task.v1.TaskService.RestartTask:output_type -> task.v1.RestartTaskResponse
	3,  // 19: task.v1.TaskService.CancelTask:output_type -> task.v1.CancelTaskResponse
	5,  // 20: task.v1.TaskService.RegisterConnection:output_type -> task.v1.RegisterConnectionResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_v1_task_proto_init() }
func file_api_proto_v1_task_proto_init() {
	if File_api_proto_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_task_proto_rawDesc), len(file_api_proto_v1_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_task_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_task_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_task_proto_msgTypes,
	}.Build()
	File_api_proto_v1_task_proto = out.File
	file_api_proto_v1_task_proto_goTypes = nil
	file_api_proto_v1_task_proto_depIdxs = nil
}
